<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>VoloAbp.OTel</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\VoloAbp.OTel.Domain\VoloAbp.OTel.Domain.csproj" />
    <ProjectReference Include="..\VoloAbp.OTel.Application.Contracts\VoloAbp.OTel.Application.Contracts.csproj" />
    <ProjectReference Include="..\VoloAbp.OTel\VoloAbp.OTel.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.PermissionManagement.Application" Version="9.3.6" />
    <PackageReference Include="Volo.Abp.FeatureManagement.Application" Version="9.3.6" />
    <PackageReference Include="Volo.Abp.SettingManagement.Application" Version="9.3.6" />
    <PackageReference Include="Volo.Abp.Account.Application" Version="9.3.6" />
    <PackageReference Include="Volo.Abp.Identity.Application" Version="9.3.6" />
    <PackageReference Include="Volo.Abp.TenantManagement.Application" Version="9.3.6" />
  </ItemGroup>

</Project>
