<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>AbpCore</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Abp" Version="10.2.0" />
    <PackageReference Include="log4net" Version="3.1.0" />
    <PackageReference Include="OpenTelemetry" Version="1.15.0" />
  </ItemGroup>
</Project>
