<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <AssetTargetFallback>$(AssetTargetFallback);portable-net45+win8+wp8+wpa81;</AssetTargetFallback>
    <AssemblyName>AbpCore.OTel.Migrator</AssemblyName>
    <OutputType>Exe</OutputType>
    <PackageId>AbpCore.OTel.Migrator</PackageId>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
  </PropertyGroup>
  <ItemGroup>
    <None Update="appsettings.json;log4net.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Abp.Castle.Log4Net" Version="10.4.0" />
    <PackageReference Include="log4net" Version="3.3.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\AbpCore.OTel.Core\AbpCore.OTel.Core.csproj" />
    <ProjectReference Include="..\AbpCore.OTel.EntityFrameworkCore\AbpCore.OTel.EntityFrameworkCore.csproj" />
  </ItemGroup>
</Project>